- name: Run Datadog Synthetics tests
  uses: DataDog/synthetics-ci-github-action@87b505388a22005bb8013481e3f73a367b9a53eb
  with:
    test_search_query: tag:e2e-tests
    tunnel: false
  # यहाँ 'env' सेक्शन जोड़ें:
  env:
    DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
    DATADOG_APP_KEY: ${{ secrets.DATADOG_APP_KEY }}
